### PR TITLE
Fixed typo and updated official examples link in README.

### PR DESCRIPTION
**Pull request by JamesSkemp**
I noticed a typo in the main README file and have created it, as well as a permanently redirecting link.

Would it also be valuable to bring in the content from the main project's current https://github.com/photonstorm/phaser-examples/blob/master/README.md ?

### CODE REVIEW

**Comment by mikaturunen** [comment]
I think we should bring in most of the content from the existing README.md over and then drop in the TypeScript specific, contributors + this project's related content into it. So basically use the README.md as a starting template and convert it into more fitting format for this repo.

How would that sound?

**Comment by mikaturunen** [comment]
Anyway, merging this in as it's a solid fix.

**Comment by JamesSkemp** [comment]
Sounds good to me. Unless you had an idea of structure, I can take a look at doing a first draft today/tomorrow.

**Comment by mikaturunen** [comment]
Go for it mate. I've got my schedules booked currently but on Saturday I'll blow in some big changes :)

**Comment by JamesSkemp** [comment]
Cool. The readme draft was actually another pull request (I think the one that pulled in later commits), so my draft is actually live. All the TS language is at the top of the document.

EDIT: It was the first commit in pull request #29.

**Pull request merged**
